### ISSUE TITLE
Secondary Logo

### ISSUE THREAD

**Issue by NathanHealea** [NathanHealea/nathanhealea.com#3]
Design and create a primary logo to be used to represent myself and my "brand"

## TODO:
- [ ] Add elements and concepts to vision board
- [ ] Sketch logo by hand
- [ ] Create vector graphic of logo
- [ ] Add Logo to Branding Guide
